// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koxmgiljgjlqoeqaanul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtveG1naWxqZ2pscW9lcWFhbnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5OTYyNjYsImV4cCI6MjA3NzU3MjI2Nn0.wyo59WNO0xMN-aw33mJc_Snn6ZNpxQx6CNllBvKWAV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});